// Main layout of your application. Use it to add UI elements that are shared across all pages (e.g. nav, footer, etc)

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
